### ISSUE TITLE
Solution exercise 1.4 wrong?

### ISSUE THREAD

**Issue by louwers** [sger/gopl-solutions#1]
> print the names of all files in which each duplicated line occurs

That means you should print the duplicated lines of all the files once, with all the files that it occurs in alongside it. So while counting lines, you need to keep track of what file you are reading lines from.

I don't know of you're supposed to be able to solve these with the concepts introduced so far. Here are some other solutions:
- Uses a struct: https://github.com/joyrexus/gopl-exercises/blob/master/ch1/1.4/dup.go
- Quadratic time, which I think is really not necessary: https://github.com/vinceyuan/gopl-solutions/blob/master/ch01/ex1.4/ex1.4.go

**Comment by sger** [comment]
thanks will fix it!

**Comment by louwers** [comment]
I think you should consider using a `map[string](map[int][int]`.
